### ISSUE TITLE
Generate.py出错

### ISSUE THREAD

**Issue by 1265578519** [FunctionClub/ZBench#8]
[root@45 ~]# wget -N --no-check-certificate https://raw.githubusercontent.com/FunctionClub/ZBench/master/ZBench-CN.sh && bash ZBench-CN.sh
--2018-08-26 05:16:55--  https://raw.githubusercontent.com/FunctionClub/ZBench/master/ZBench-CN.sh
正在解析主机 raw.githubusercontent.com... 151.101.20.133
正在连接 raw.githubusercontent.com|151.101.20.133|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度：16659 (16K) [text/plain]
正在保存至: “ZBench-CN.sh”

100%[===================================================================================================================================================================================================>] 16,659      --.-K/s   in 0s      

缺少“Last-modified”文件头-- 关闭时间戳标记。
2018-08-26 05:16:55 (58.0 MB/s) - 已保存 “ZBench-CN.sh” [16659/16659])

请输入你的服务器提供商: vi^H

请确认你所在地的IP:111.58.168.80 [y/n]: n

请输入你所在地的IP: 45.63.1.15
正在安装必要的依赖，请耐心等待...
Installing Virt-What......
Installing uuid......
Installing curl......
Installing Besttrace......
Installing SpeedTest......
Installing ZPing-CN.py......
--------------------------------------------------------------------------
CPU 型号             : Virtual CPU a7769a6388d5
CPU 核心数           : 1
CPU 频率             : 2399.996 MHz
总硬盘大小           : 23.5 GB (1.8 GB Used)
总内存大小           : 995 MB (444 MB Used)
SWAP大小             : 2015 MB (0 MB Used)
开机时长             : 0 days, 2 hour 42 min
系统负载             : 0.14, 0.12, 0.11
系统                 : CentOS 6.9
架构                 : x86_64 (64 Bit)
内核                 : 2.6.32-696.30.1.el6.x86_64
虚拟化平台           : kvm
--------------------------------------------------------------------------
硬盘I/O (第一次测试) : 292 MB/s
硬盘I/O (第二次测试) : 344 MB/s
硬盘I/O (第三次测试) : 346 MB/s
--------------------------------------------------------------------------
节点名称                  IP地址            下载速度            延迟      
CacheFly                  205.234.175.175   86.2MB/s            1.272 ms    
Linode, Tokyo, JP         106.187.96.148    10.4MB/s            175.670 ms  
Linode, Singapore, SG     139.162.23.4      6.35MB/s            266.472 ms  
Linode, London, UK        176.58.107.39     18.8MB/s            77.054 ms   
Linode, Frankfurt, DE     139.162.130.8     16.4MB/s            83.331 ms   
Linode, Fremont, CA       50.116.14.9       21.7MB/s            70.980 ms   
Softlayer, Dallas, TX     173.192.68.18     39.3MB/s            44.303 ms   
Softlayer, Seattle, WA    67.228.112.250    27.1MB/s            62.252 ms   
Softlayer, Frankfurt, DE  159.122.69.4      13.8MB/s            82.102 ms   
Softlayer, Singapore, SG  119.81.28.170     7.09MB/s            259.518 ms  
Softlayer, HongKong, CN   119.81.130.170    8.02MB/s            216.366 ms  
--------------------------------------------------------------------------
节点名称                  上传速度          下载速度            延迟      
西安电信                  11.44 Mbit/s      42.24 Mbit/s        494.031 ms 
上海联通                  4.27 Mbit/s       22.17 Mbit/s        259.847 ms 
北京电信                  18.00 Mbit/s      38.59 Mbit/s        271.781 ms 
湖南电信                  2.92 Mbit/s       0.60 Mbit/s         000.000 ms 
--------------------------------------------------------------------------
合肥        : 258.02 ms  北京        : 226.32 ms  武汉        : 231.03 ms  
昌吉        : 398.87 ms  成都        : Fail       上海        : 267.27 ms  
太原        : 274.04 ms  杭州        : 321.79 ms  宁夏        : 274.16 ms  
呼和浩特    : 318.76 ms  南昌        : Fail       拉萨        : 290.77 ms  
乌鲁木齐    : 333.85 ms  天津        : 330.31 ms  襄阳        : Fail       
郑州        : 258.02 ms  沈阳        : 268.47 ms  兰州        : 255.7 ms   
哈尔滨      : 276.85 ms  宁波        : Fail       苏州        : 270.18 ms  
济南        : 258.78 ms  西安        : 265.68 ms  西宁        : 252.6 ms   
重庆        : 347.26 ms  深圳        : 296.37 ms  南京        : 279.46 ms  
长沙        : 236.47 ms  长春        : 259.98 ms  福州        : 253.13 ms  
--------------------------------------------------------------------------
Traceback (most recent call last):
  File "Generate.py", line 625, in <module>
    traceroute_to_table("/tmp/shm.txt")
  File "Generate.py", line 73, in traceroute_to_table
    string = string + template.format(i,x["ip"],x["route"],x["isp"],x["asn"],x["latency"]) + "\n"
ValueError: zero length field name in format
cat: /tmp/shm.txt_table: 没有那个文件或目录
cat: /tmp/sht.txt_table: 没有那个文件或目录
cat: /tmp/shu.txt_table: 没有那个文件或目录
cat: /tmp/gdm.txt_table: 没有那个文件或目录
cat: /tmp/gdt.txt_table: 没有那个文件或目录
cat: /tmp/gdu.txt_table: 没有那个文件或目录
PASS在线查看测评报告：https://zbench.kirito.moe/record-cn.php?IKEY=13688
您的测评报告已保存在 /root/report.html

你想现在查看您的测评报告吗? [y/n]: y

访问 http://45.63.1.15:8001/index.html 查看您的测试报告，按 Ctrl + C 退出
Serving HTTP on 0.0.0.0 port 8001 ...

**Comment by KiritoMiao** [comment]
正在重构
